
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.lang.reflect.Array;
import java.util.Scanner;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ganesh
 */
public class Catalogue extends javax.swing.JFrame {
   public DefaultListModel<String> listModelName;
     public DefaultListModel<String> listModelPrice;
     public DefaultListModel<String> listModelSupplier;
    /**
     * Creates new form Catalogue
     */
    public Catalogue() {
        initComponents();
        boolean cont=true;
        int i=0;
        int j=0;
       ProductDetails[] prod;
        try{    
        FileInputStream fout = new FileInputStream("ProductList.dat");
        ObjectInputStream oos=new ObjectInputStream(fout);
       prod=(ProductDetails[])oos.readObject();
        listModelName = new DefaultListModel<>();
        listModelPrice = new DefaultListModel<>();
        
        try
        { j=0;
            while(prod[j++].name!=null);
        }catch(Exception e){
            
        }
        
         while(i<j-1)
         {   System.out.print(prod[i].stock);
             listModelName.addElement(prod[i].name);
             listModelPrice.addElement(prod[i++].price +"");
            // listModelSupplier.addElement(prod[j++].Supplier);
         }
         jList1.setModel(listModelName);
         jList2.setModel(listModelPrice);
       
       }catch(Exception e){
           System.out.print(e);
       }
        
        
       
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        addedItem = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(addedItem);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Checkout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jList1.setToolTipText("");
        jScrollPane1.setViewportView(jList1);
        jList1.getAccessibleContext().setAccessibleName("Products");

        jScrollPane3.setViewportView(jList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 static public DefaultListModel<String> listModelAdd=new DefaultListModel<>();
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel1.setText("");
        int k,i,j=0;
        ProductDetails[] prod=new ProductDetails[100];
        try{    
        FileInputStream fout = new FileInputStream("ProductList.dat");
        ObjectInputStream oos=new ObjectInputStream(fout);
       prod=(ProductDetails[])oos.readObject();
         }catch(Exception e){
             System.out.print(e);
         }
        try
        { j=0;
            while(prod[j++].name!=null);
        }catch(Exception e){
            
        }

       listModelAdd.addElement(jList1.getSelectedValue());
       k=0;
         for(k=0;k<listModelAdd.size();k++){
             i=0;
         while(i<j-1)
         {
             if(prod[i].name.equals(listModelAdd.elementAt(k)))
             {
                 if(!prod[i].flag){
                    listModelAdd.remove(k);
                    jLabel1.setText("Out of Stock");
                 }
                 else
                 {
                     prod[i].stock--;
                     if(prod[i].stock<1)
                         prod[i].flag=false;
                 }
                 break;
             }
             i++;
         }
         }
         if(!jLabel1.getText().equals("Out of Stock"))
       addedItem.setModel(listModelAdd);
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
         int k,i,j=0;
        ProductDetails[] prod=new ProductDetails[100];
        try{    
        FileInputStream fout = new FileInputStream("ProductList.dat");
        ObjectInputStream oos=new ObjectInputStream(fout);
       prod=(ProductDetails[])oos.readObject();
         }catch(Exception e){
             System.out.print(e);
         }
        try
        { j=0;
            while(prod[j++].name!=null);
        }catch(Exception e){
            
        }
        i=0;
       listModelAdd.removeElement(addedItem.getSelectedValue());
       
         while(i<j-1)
         {
             if(prod[i].name.equals(addedItem.getSelectedValue()))
             {
                 prod[i].stock++;
                 break;
             }
             i++;
         
         }
        
       addedItem.setModel(listModelAdd);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Scanner scan=new Scanner(System.in);
       
       ProductDetails[] prod;
         prod = new ProductDetails[100];
      /*for(int i=0;i<15;i++)
       {  prod[i]=new ProductDetails();
           System.out.println("Enter Name");
           prod[i].name=scan.next();
           System.out.println("Price:");
           prod[i].price=Integer.parseInt(scan.next());
           System.out.println("supplier:");
           prod[i].Supplier=scan.next();
            System.out.println("Stock:");
           prod[i].stock=Integer.parseInt(scan.next());;
           
       }
       try{    
        FileOutputStream fout = new FileOutputStream("ProductList.dat");
        ObjectOutputStream oos=new ObjectOutputStream(fout);
        oos.writeObject(prod);
 
       }catch(Exception e){
           System.out.print(e);
       }*/
      UserDetails[] det=new UserDetails[3];
      /*for(int i=0;i<3;i++)
      {   det[i]=new UserDetails();
          System.out.println("UN:");
          det[i].userName=scan.next();
          det[i].pwd=scan.next();
          det[i].address=scan.next();
      }
           try{    
        FileOutputStream fout = new FileOutputStream("UserList.dat");
        ObjectOutputStream oos=new ObjectOutputStream(fout);
        oos.writeObject(det);
 
       }catch(Exception e){
           System.out.print(e);
       }*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogue().setVisible(true);
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> addedItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
